config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExportReportWithRakeSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('Edit Password', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('Sign Up', new_registration_path(:user)) %> |
      <%= link_to('Sign In', new_session_path(:user)) %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users Index</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.email %> | <%= user.created_at %></li>
  <% end %>
</ul>